### ISSUE TITLE
Unable to setup Grafana dashboard

### ISSUE THREAD

**Issue by jithin03** [jvstein/bitcoin-prometheus-exporter#21]
When I try to import the Dashboard on Grafana I am asked to add the data source. When I try to add the exporter as a Prometheus data source in Graphana it shows a bad gateway
![image](https://user-images.githubusercontent.com/68288007/126904510-32c00fdb-b449-411a-b7a2-91b57207f1c2.png)
Am I missing something?

**Comment by jvstein** [comment]
The data source should be a pointer to your Prometheus server.

In my Grafana container I have a `/etc/grafana/provisioning/datasources/prometheus.yaml` file with something like this. There's probably a way to do it through the Grafana UI as well.

```
apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    isDefault: true
    access: proxy
    url: https://prometheus.example.com
```
